
#pragma once

#define RENDERDOC_UI_EXE_NAME "TestName"
#define RENDERDOC_UI_EXE_WSTR L"TestName"
#define RENDERDOC_UI_EXE_FULL RENDERDOC_UI_EXE_NAME ".exe"
#define RENDERDOC_UI_EXE_WSTR_FULL RENDERDOC_UI_EXE_WSTR L".exe"

#define RENDERDOC_CORE_DLL_NAME "rdoc_core"
#define RENDERDOC_CORE_DLL_FULL RENDERDOC_CORE_DLL_NAME ".dll"

#ifndef RENDERDOC_REPLAY_MARKER_SYMBOL
#define RENDERDOC_REPLAY_MARKER_SYMBOL rdoc_core__replay__marker
#endif
